version: "3"

services:
  xs-server:
    image: xsocks:0.1.0-alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 10M
        reservations:
          cpus: '0.25'
          memory: 2M
      restart_policy:
        max_attempts: 0
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - ../config.json:/usr/local/xsocks/etc/config.json
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    command: bin/xs-server -c etc/config.json
