version: "3"

services:
  xsocks:
    build: .
    image: xsocks/builds/asuswrt-merlin.ng:${XSOCKS_VERSION}
    deploy:
      restart_policy:
        max_attempts: 0
    privileged: true
    restart: on-failure:0
    volumes:
      - /etc/localtime:/etc/localtime
      - ${ROOT}:/tmp/xsocks
      - ${AM_TOOLCHAINS_PATH}:/tmp/am-toolchains
    working_dir: /tmp/xsocks
    environment:
      - HOST=${HOST}
      - ROOT=/tmp/xsocks
    command: /tmp/xsocks/builds/asuswrt-merlin.ng/build.sh
